name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOTNET_VERSION: '8.0.x'
  BINARY_MODULE_PATH: '.'
  MODULE_NAME: 'PSDataverse'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: |
        pushd '${{ env.BINARY_MODULE_PATH}}'
        dotnet restore
        popd
      
    - name: Build
      run: |
        pushd '${{ env.BINARY_MODULE_PATH}}'
        dotnet build --no-restore --configuration Release --output ./output/bin
        popd
      
    - name: Test (.NET)
      run: |
        pushd '${{ env.BINARY_MODULE_PATH}}'
        dotnet test --no-build --verbosity normal --output ./output/bin
        popd
        
    - name: Prepare package
      shell: pwsh
      run: |
        pushd '${{ env.BINARY_MODULE_PATH}}'
        Copy-Item "./src/Module/*" ./output
        popd
