name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  verify-release-candidate:
    uses: ./.github/workflows/verify-package.yml
