name: Build -> Test -> Publish

on:
  #pull_request:
  #  branches: [ "main", "release/*" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  BINARY_MODULE_PATH: '.'
  MODULE_NAME: 'PSDataverse'

jobs:
  build:
    
    runs-on: ubuntu-latest
    environment: 
      name: PowerShell Gallery

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: |
        pushd '${{ env.BINARY_MODULE_PATH}}'
        dotnet restore
        popd
      
    - name: Test (.NET)
      run: dotnet test --no-restore --configuration Release --verbosity normal
        
    - name: Build package
      shell: pwsh
      run: |
        Import-Module ./build.psm1 -Force
        Start-PSDataverseBuild -Output ./output/${{ env.MODULE_NAME }}

    - name: Smoke-test package
      shell: pwsh
      run: |
        ./tests/SmokeTest-Module.ps1 -ModulePath ./output/${{ env.MODULE_NAME }}/PSDataverse.psd1
        
    - name: Publish
      shell: pwsh
      run: |
        pushd '${{ env.BINARY_MODULE_PATH}}'
        Publish-Module -Path ./output/${{ env.MODULE_NAME }} -NuGetApiKey "${{ secrets.POWERSHELL_GALLERY_API_KEY }}"
        popd
        
        
    
        
